### PR TITLE
adds sprite

### PR DESCRIPTION
**Pull request by KaterynaVeselova**

### CODE REVIEW

**Comment by KaterynaVeselova** [comment]
adds sprite.svg

**Review by KaterynaVeselova — COMMENTED** [review]
adds sprite.svg

**Comment by KaterynaVeselova** [comment]
adds sprite.svg

**Comment by Anastasiia-stzn** [comment]
allright

**Comment by KaterynaVeselova** [comment]
after Anastasia's and Inga's reviews

**Review by Anastasiia-stzn — APPROVED** [review]

**Pull request merged**
